export const Path = {
    Root: '/',
    Main: '/main',
    Auth: '/auth',
    Feedbacks: '/feedbacks',
    Registration: '/auth/registration',
    Result: '/result',
    Success: '/result/success',
    Error: '/result/error',
    ErrorUserExist: '/result/error-user-exist',
    ErrorLogin: '/result/error-login',
    ErrorCheckEmailNoExist: '/result/error-check-email-no-exist',
    ErrorCheckEmail: '/result/error-check-email',
    SuccessChangePassword: '/result/success-change-password',
    ErrorChangePassword: '/result/error-change-password',
    ConfirmEmail: '/auth/confirm-email',
    ChangePassword: '/auth/change-password',
    Calendar: '/calendar',
    Profile: '/profile',
    Settings: '/settings',
    Training: '/training',
    Achievements: '/achievements',
};
